### ISSUE TITLE
XSD er ikke i samsvar med dokumentasjon

### ISSUE THREAD

**Issue by Olethros** [Utdanningsdirektoratet/pifu#14]
I dokumentasjon under P3.13.2.1 er en type av _legalName_ obligatorisk for organisasjon og organisasjonsenhet. Den er ikke gjenspeilet i XSD. Hvilket er riktig/autoritativ her? Dokumentasjonen eller XSD?

**Comment by torleifg** [comment]
Dokumentasjon skal være autorativ. _legalName_ gjenspeiles i XSD, men ikke som obligatorisk. Gruppeobjektet brukes også til å beskrive andre typer grupper enn kommuner og skoler, f.eks. undervisningsgrupper og basisklasser, hvor denne informasjonen ikke er obligatorisk. XSD-en håndterer ikke såpass kompleks logikk per i dag.
