### ISSUE TITLE
PIFU IMS 1.1 er ikke i samsvar med FEIDE-krav

### ISSUE THREAD

**Issue by torharaldlothe** [Utdanningsdirektoratet/pifu#15]
4.3.3   Utvidelser på trinn, utdanningsprogram, programområde og fag inneholder krav om GREP-koder. 
4.3.2   Utvidelser på basisgruppe, undervisningsgruppe og kontaktlærergruppe inneholder ikke krav om GREP-koder.
GREP-koder for undervisningsgrupper er påkrevd ift FEIDEs informasjonsmodell for FEIDE 1.6 så det ville være naturlig at PIFU IMS, som oftest benyttes ift overføring av data til FEIDE, har tilsvarende krav.

Eller er det noe som er misforstått her? 
med vennlig hilsen

**Comment by torleifg** [comment]
Det er riktig som du sier. PIFU-IMS 1.1 reflekterer kravet om Grep-koder som kom med Feide 1.5. Med Feide 1.6 kom kravet om gruppeinformasjon, og at undervisningsgrupper skal være tilknyttet en fagkode fra Grep-kodeverket. 

Vi har en branch på dette GitHub-repositoriet som heter develop-latest. Denne endringen er gjenspeilet i dokumentasjonen (Markdown) som finnes der, og vil bli tatt inn i en ny versjon av PIFU-IMS. 

Grep-koder på undervisningsgrupper ble også spilt inn som et behov før sommeren, men da i en annen sammenheng enn Feide. Endringen innebærer kun oppdatering av dokumentasjon, og er i bruk hos enkelte aktører.

**Comment by torharaldlothe** [comment]
Takk skal du ha!
