### ISSUE TITLE
Fådelte skoler og sammenholdte klasser

### ISSUE THREAD

**Issue by AMNytroen** [Utdanningsdirektoratet/pifu#20]
Mange norske kommuner har små skoler med klasser der elevene hører til ulike årstrinn. Dette gjøres både av hensyn til planleggingen og den daglige undervisningen. 

La meg gi et eksempel:
på Den lille skolen i kommunene Kommune går det 13 elever. 6 av disse elevene går i klassen Småskolen.  Der er det 1 elev som hører til 1. trinn,  2 elever på 2.trinn, 3 elever på 3.trinn  og 1 elev på 4.trinn. Når elevene har f eks engelsk sammen, vil elevgruppa "Småskolen engelsk" ha mer enn en fagkode knyttet opp mot seg , ENG0001, ENG0002, ENG0003, ENG0004. Læreren er knyttet mot gruppa.
Hvordan blir dette håndtert i  PIFUutrekket ?

**Comment by torleifg** [comment]
Anbefalingen er at den enkelte elev knyttes til riktig årstrinn og fagkode (undervisningsgruppe) ved føring av grupper i skoleadministrative systemer. Fådelte grupper bør registreres som basisgrupper/klasser. Anbefalingen er tett knyttet til Feide og behovet for persontilpassede tjenester.

Fra Feide 1.5.x ble det obligatorisk å legge inn årstrinn som eleven får undervisning på, dvs. nivået, ikke basisgruppe/klasse. En elev kan fint ha flere årstrinn registrert på seg, men intensjonen er at det er årtrinnene denne mottar undervisning på.

Fra Feide 1.6 ble det obligatorisk å registrere basisgrupper og undervisningsgrupper. For basisgruppene/klassene er det ikke knyttet noen grep-kode, så der er det ikke noe problem at elever på flere nivåer er knyttet til samme basisgruppe. For undervisningsgruppe skal grep-koden til faget eleven tar være registrert. 

Eks. undervisningsgruppe i Engelsk 1. til 4. trinn:
1 elev med gruppeid 'Engelsk1-4', med grepkode 'ENG0001'
2 elever med gruppeid 'Engelsk1-4', med grepkode 'ENG0002'
3 elever med gruppeid 'Engelsk1-4', med grepkode 'ENG0003'
1 elev med gruppeid 'Engelsk1-4', med grepkode 'ENG0004'

Intensjonen er at eleven skal få tilgang til de riktige ressursene på de riktige faget/fagnivåene/lærebøkene hos forskjellige innholdsleverandører, samt at lærere skal kunne håndtere gruppene sine i disse tjenestene.
